create table
  public.quiz_question_options (
    id uuid not null default gen_random_uuid (),
    created_at timestamp with time zone not null default now(),
    quiz_question_id uuid null default gen_random_uuid (),
    value text null,
    "order" numeric null,
    is_correct boolean null,
    constraint quiz_question_options_pkey primary key (id),
    constraint quiz_question_options_quiz_question_id_fkey foreign key (quiz_question_id) references quiz_questions (id)
  ) tablespace pg_default;


  create table
  public.quiz_questions (
    id uuid not null default gen_random_uuid (),
    created_at timestamp with time zone not null default now(),
    resource_id uuid null default gen_random_uuid (),
    question text null,
    answer text null,
    expected_duration numeric null,
    point_value numeric null,
    "order" numeric null,
    type text null,
    constraint quiz_questions_pkey primary key (id),
    constraint quiz_questions_resource_id_fkey foreign key (resource_id) references resources (id)
  ) tablespace pg_default;

  create table
  public.resource_references (
    id uuid not null default gen_random_uuid (),
    created_at timestamp with time zone not null default now(),
    library_resource_id uuid null default gen_random_uuid (),
    generated_resource_id uuid null default gen_random_uuid (),
    constraint resource_references_pkey primary key (id)
  ) tablespace pg_default;

  create table
  public.resource_tags (
    id uuid not null default gen_random_uuid (),
    created_at timestamp with time zone not null default now(),
    resource_id uuid null default gen_random_uuid (),
    value text null,
    constraint resource_tags_pkey primary key (id),
    constraint resource_tags_resource_id_fkey foreign key (resource_id) references resources (id)
  ) tablespace pg_default;

  create table
  public.resources (
    id uuid not null default gen_random_uuid (),
    created_at timestamp with time zone not null default now(),
    last_modified timestamp with time zone null default now(),
    url text null,
    value text null,
    name text null,
    description text null,
    type text null,
    origin text not null default 'USER'::text,
    archived boolean not null default false,
    expected_duration numeric null,
    grade_level text null,
    constraint resources_pkey primary key (id)
  ) tablespace pg_default;


  create table
  public.user_resources (
    id bigint generated by default as identity not null,
    created_at timestamp with time zone not null default now(),
    user_id uuid null default gen_random_uuid (),
    resource_id uuid null default gen_random_uuid (),
    constraint user_resources_pkey primary key (id),
    constraint user_resources_resource_id_fkey foreign key (resource_id) references resources (id),
    constraint user_resources_user_id_fkey foreign key (user_id) references users (id)
  ) tablespace pg_default;


  create table
  public.users (
    id uuid not null default gen_random_uuid (),
    created_at timestamp with time zone not null default now(),
    first_name text null,
    last_name text null,
    title text null,
    complete boolean null,
    constraint users_pkey primary key (id),
    constraint users_id_fkey foreign key (id) references auth.users (id)
  ) tablespace pg_default;